name: dependencies
on: pull_request
jobs:
  changeset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: "the-guild-org/changesets-dependencies-action@v1.1.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}