name: release
on:
  push:
    branches:
      - main
env:
  CI: true

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          fetch-depth: 0
      - name: setup pnpm
        uses: pnpm/action-setup@537643d491d20c2712d11533497cb47b2d0eb9d5 # tag=v2.2.3
      - name: setup node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - name: setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
      - name: install dependencies
        run: pnpm install
      - name: create and publish versions
        uses: frickegroup/changesets-action@cbc5ff3569ae9861100a48b290f4e9c1b94e45b5 # tag=v1.3.3
        with:
          setupGitUser: true
          title: "Upcoming Release Changes"
          commit: "chore(release): update monorepo packages"
          createGithubReleases: aggregate
          version: pnpm prerelease
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}